name: scraper
channels:
  - defaults
dependencies:
  - python=3.10
  - selenium=4.24.0
  - requests=2.32.4
  - pandas=2.3.1
  - beautifulsoup4=4.13.4
  - lxml=5.3.0
  - tqdm=4.67.1
  - pip
  - pip:
    - webdriver-manager==3.8.6
    - playwright==1.42.0
